"""initial revision

Revision ID: 9b75448754a1
Revises:
Create Date: 2025-03-24 12:59:44.256486

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b75448754a1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tapes",
        sa.Column("tape_id", sa.String(), nullable=False),
        sa.Column("tape_type", sa.String(), nullable=True),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("purchase_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("tape_id"),
    )
    op.create_table(
        "files",
        sa.Column("filebase", sa.String(), nullable=False),
        sa.Column("filepath", sa.String(), nullable=True),
        sa.Column("tape_id", sa.String(), nullable=False),
        sa.Column("obsid", sa.BigInteger(), nullable=True),
        sa.Column("jd_start", sa.Float(), nullable=True),
        sa.Column("jd", sa.BigInteger(), nullable=True),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("write_date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tape_id"], ["tapes.tape_id"]),
        sa.PrimaryKeyConstraint("filebase"),
    )
    op.create_index(op.f("idx_jd"), "files", ["jd"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_jd"), table_name="files")
    op.drop_table("files")
    op.drop_table("tapes")
    # ### end Alembic commands ###
